server:
  servlet:
    context-path: /accounts
  port: 8030
logging:
  level:
    com.springboot.app: DEBUG
spring:
  data:
    mongodb:
      host: mongo
      database: test
      port: 27017
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
account:
  not-exists: Account does not exists
  insufficient-balance: Balance is insufficient
  valid: Account is valid